/* exponentialSmoothingAlpha tests */
SELECT exponentialSmoothingAlpha()(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(0.5, 0.5)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(-1)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(2)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(0.5) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlpha(0)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlpha(0.2)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlpha(0.5)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 3 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlpha(0.8)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 4 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlpha(1)(value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 4 + rand() % 100 / 100 - 0.5  as value from numbers_mt(100)) OFFSET 99;

/* exponentialSmoothingAlphaWithTime tests */
SELECT exponentialSmoothingAlphaWithTime()(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(0.5, 0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(-1)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(2)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(0.5)(value) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(0.5)(value, timestamp, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(0.5)(timestamp, value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTime(0)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTime(0.2)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTime(0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number div 2 as timestamp, number * 3 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTime(0.8)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number % 2 as timestamp, number * 4 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTime(1)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number % 2 as timestamp, number * 4 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;

/* exponentialSmoothingAlphaWithTimeFillGaps tests */
SELECT exponentialSmoothingAlphaWithTimeFillGaps()(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5, 0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(-1)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(2)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(value) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(value, timestamp, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(timestamp, value) over (ORDER BY timestamp ASC) from (SELECT number as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError BAD_ARGUMENTS }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number div 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError INCORRECT_DATA }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number % 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99; -- { serverError INCORRECT_DATA }
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.2)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 2 as timestamp, number * 2 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.5)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 3 as timestamp, number * 3 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTimeFillGaps(0.8)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 4 as timestamp, number * 4 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
SELECT exponentialSmoothingAlphaWithTimeFillGaps(1)(value, timestamp) over (ORDER BY timestamp ASC) from (SELECT number * 4 as timestamp, number * 4 + rand() % 100 / 100 - 0.5 as value from numbers_mt(100)) OFFSET 99;
